### ISSUE TITLE
client.getOnlySource(SourceType.HDFS) call failed with stack trace

### ISSUE THREAD

**Issue by monfor** [cloudera/navigator-sdk#43]
I have the following code snippet to retrieve the HDFS source type. When executing my program in the Cloudera AWS clusters, I got the following stack trace.

        NavApiCient client = plugin.getClient();
        Source hdfsSource = client.getOnlySource(SourceType.HDFS);
  
============
16:31:08.006 [main] INFO  c.w.i.cloudera.SensitiveData - Adapter started.
Exception in thread "main" org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Numeric value (2160620923) out of range of int
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@cad7e2b; line: 17, column: 40] (through reference chain: com.cloudera.nav.sdk.client.SourceAttrs["sourceExtractIteration"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2160620923) out of range of int
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@cad7e2b; line: 17, column: 40] (through reference chain: com.cloudera.nav.sdk.client.SourceAttrs["sourceExtractIteration"])
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readJavaType(MappingJackson2HttpMessageConverter.java:228)
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.read(MappingJackson2HttpMessageConverter.java:220)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:95)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:795)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:779)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:559)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:512)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:454)
	at com.cloudera.nav.sdk.client.NavApiCient.getAllSources(NavApiCient.java:82)
	at com.cloudera.nav.sdk.client.NavApiCient.loadAllSources(NavApiCient.java:220)
	at com.cloudera.nav.sdk.client.NavApiCient.getSourcesForType(NavApiCient.java:172)
	at com.cloudera.nav.sdk.client.NavApiCient.getOnlySource(NavApiCient.java:163)
	at com.waterlinedata.integration.cloudera.SensitiveData.Main(SensitiveData.java:154)
	at com.waterlinedata.integration.cloudera.SensitiveData.main(SensitiveData.java:237)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2160620923) out of range of int
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@cad7e2b; line: 17, column: 40] (through reference chain: com.cloudera.nav.sdk.client.SourceAttrs["sourceExtractIteration"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2094)
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readJavaType(MappingJackson2HttpMessageConverter.java:225)
	... 13 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (2160620923) out of range of int
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@cad7e2b; line: 17, column: 40]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:847)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:643)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:319)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:301)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	... 19 more
[waterline@ip-192-168-100-254 bin]$

**Comment by changhiskhan** [comment]
@monfor this got lost in the shuffle in the holiday season. As you can see from the source, `client.getOnlySource` is a convenience function to make testing/examples easier. As the method name suggests, it assume you have 1 and only 1 Source of the given SourceType that the server knows about. If you're not certain how many you have, you should be using the `getSourcesForType` method instead.

**Comment by monfor** [comment]
After changing the call and it still crashes. See the new stack trace below. You can see that I have replaced the call with the following:

      Collection<Source> hdfsSources = client.getSourcesForType(SourceType.HDFS);
=================
Exception in thread "main" org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Numeric value (2978969079) out of range of int
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@6848db81; line: 17, column: 40] (through reference chain: com.cloudera.nav.sdk.client.SourceAttrs["sourceExtractIteration"]); nested exception is com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2978969079) out of range of int
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@6848db81; line: 17, column: 40] (through reference chain: com.cloudera.nav.sdk.client.SourceAttrs["sourceExtractIteration"])
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readJavaType(MappingJackson2HttpMessageConverter.java:228)
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.read(MappingJackson2HttpMessageConverter.java:220)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:95)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:795)
	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:779)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:559)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:512)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:454)
	at com.cloudera.nav.sdk.client.NavApiCient.getAllSources(NavApiCient.java:82)
	at com.cloudera.nav.sdk.client.NavApiCient.loadAllSources(NavApiCient.java:220)
	at com.cloudera.nav.sdk.client.NavApiCient.getSourcesForType(NavApiCient.java:172)
	at com.waterlinedata.integration.cloudera.SensitiveData.Main(SensitiveData.java:207)
	at com.waterlinedata.integration.cloudera.SensitiveData.main(SensitiveData.java:264)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (2978969079) out of range of int
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@6848db81; line: 17, column: 40] (through reference chain: com.cloudera.nav.sdk.client.SourceAttrs["sourceExtractIteration"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:197)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1311)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:297)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:18)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2094)
	at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readJavaType(MappingJackson2HttpMessageConverter.java:225)
	... 12 more
Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (2978969079) out of range of int
 at [Source: org.apache.http.client.entity.LazyDecompressingInputStream@6848db81; line: 17, column: 40]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:532)
	at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:847)
	at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:643)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:306)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:319)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:301)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:98)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	... 18 more

**Comment by changhiskhan** [comment]
Oh I see. I misread the error before. It looks like Source.sourceExtractIteration should be a long but was declared as Integer. Could you try changing that variable to Long (and also change the getter/setter as appropriate) and give it a shot? Thanks again for the feedback!
