### ISSUE TITLE
Unable to run examples

### ISSUE THREAD

**Issue by manucbilagi** [cloudera/navigator-sdk#56]
Whenever i am running IncrementalExtraction.java i get this error - 

2016-03-18 19:49:06,322 DEBUG [main:client.RestTemplate@78] Created POST request for "http://10.**.**.**:7187/api/v3/entities/paging"
2016-03-18 19:49:06,345 DEBUG [main:client.RestTemplate@679] Setting request Accept header to [application/json, application/*+json]
2016-03-18 19:49:06,361 DEBUG [main:client.RestTemplate@756] Writing [com.cloudera.nav.sdk.client.MetadataQuery@4e6a446c] using [org.springframework.http.converter.json.MappingJackson2HttpMessageConverter@22b236ac]
2016-03-18 19:49:06,461  WARN [main:client.RestTemplate@591] POST request for "http://10.**.**.**:7187/api/v3/entities/paging" resulted in 405 (Method Not Allowed); invoking error handler
Exception in thread "main" org.springframework.web.client.HttpClientErrorException: 405 Method Not Allowed
	at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:91)
	at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:598)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:556)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:512)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:454)
	at com.cloudera.nav.sdk.client.NavApiCient.queryNav(NavApiCient.java:143)
	at com.cloudera.nav.sdk.client.NavApiCient.getEntityBatch(NavApiCient.java:122)
	at com.cloudera.nav.sdk.client.MetadataResultIterator.getResultsBatch(MetadataResultIterator.java:123)
	at com.cloudera.nav.sdk.client.MetadataResultIterator.getNextBatch(MetadataResultIterator.java:104)
	at com.

**Comment by manucbilagi** [comment]
Kindly help me with this

**Comment by changhiskhan** [comment]
I think it's because you're using v3 of the API which doesn't support the cursor-based paging. Try switching to API v6 or above.

**Comment by manucbilagi** [comment]
Hi Chang, thanks for your response. How to upgrade to latest version ? Currently I am using CDH 5.4.3 version.

**Comment by manucbilagi** [comment]
@changhiskhan  can you please let me know how i can upgrade to >v6 . Currently i am using CDH 5.4.2 which has Cloudera navigator running on Version 2.3.1

**Comment by changhiskhan** [comment]
hi @manucbilagi sorry for the late reply I've been hosed this past week. You need to upgrade Cloudera Manager (http://www.cloudera.com/documentation/enterprise/5-5-x/topics/cm_ag_upgrading_cm.html)

**Comment by changhiskhan** [comment]
Closing this issue. Let me know if you need more help with upgrading
