### ISSUE TITLE
Lineage for Custom HDFS entities - ClassCastException

### ISSUE THREAD

**Issue by tkistul** [cloudera/navigator-sdk#71]
Using SDK v 1.1

Created 2 custom HDFS entities and Data Flow Relation between them.

When Trying to view lineage in Navigator Admin UI, getting exception below.

Please advise.

java.lang.ClassCastException: com.cloudera.nav.core.model.CustomEntity cannot be cast to com.cloudera.nav.hdfs.model.FSEntity
	at com.cloudera.nav.lineage.processor.AddFileDirectoryRelation.apply(AddFileDirectoryRelation.java:26)
	at com.cloudera.nav.lineage.phases.LineagePostProcessorPhase.executePhase(LineagePostProcessorPhase.java:42)
	at com.cloudera.nav.lineage.phases.AbstractLineageTraversalPhase.execute(AbstractLineageTraversalPhase.java:71)
	at com.cloudera.nav.lineage.phases.AbstractLineageTraversalPhase.execute(AbstractLineageTraversalPhase.java:64)
	at com.cloudera.nav.lineage.LineageBuilder.getLineageGraph(LineageBuilder.java:207)
	at com.cloudera.nav.api.v9.impl.Lineage3ResourceV9Impl.getLineage(Lineage3ResourceV9Impl.java:81)
	at sun.reflect.GeneratedMethodAccessor601.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:64)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy113.getLineage(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:198)

********************************************

GET request to "/api/v9/lineage3?entityIds=91816f1d1e72efbe33102ebc02b37d0a&options=0&offset=-2500&length=5000" using data "" failed with error 500:"Server Error" and responseText "{
  "message" : "com.cloudera.nav.core.model.CustomEntity cannot be cast to com.cloudera.nav.hdfs.model.FSEntity"

**Comment by aadarshjajodia** [comment]
Fixed in v2.0
